server:
  port: 8080
  servlet:
    context-path: /api
spring:
  application:
    name: car
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.100.238.247:3306/qichezhijia?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: hxp
    password: Jb123456
  #配置jpa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    serialization:
      indent_output: true